Repository Code-the-Dream-School/ee-prac-team2-back, pull requests merged in 2023-12, with the labels that each got.

#44 28: Add login endpoint
  README.md
  src/controllers/authController.js
  src/models/User.js
  src/routes/activitiesRouter.js
  src/routes/authRouter.js
Labels: feature

#58 Fix CODEOWNERS rule
  .github/CODEOWNERS
Labels: devops, bug

#56 53: Pull activities from https://boredapi.com
  package-lock.json
  package.json
  src/controllers/activitiesController.js
  src/swagger.yaml
Labels: refactor, feature

#65 61: Please add Activity IDs to /activities response JSON
  src/controllers/activitiesController.js
Labels: bug

#67 Updated all req.user.userID references
  src/controllers/groupsController.js
Labels: refactor, bug

#64 47: Implement Passportjs
  package-lock.json
  package.json
  src/app.js
  src/controllers/activitiesController.js
  src/controllers/authController.js
  src/controllers/eventsController.js
  src/controllers/usersController.js
  src/middleware/authHandler.js
  src/routes/authRouter.js
  src/routes/usersRouter.js
  src/utils/generateCookie.js
  src/utils/passportConfig.js
Labels: refactor, feature

#71 50: Activity voting window
  package-lock.json
  package.json
  src/controllers/eventsController.js
  src/server.js
  src/swagger.yaml
  src/utils/chosenActivityConfig.js
Labels: refactor, feature
